import type { Metadata } from "next";
import { Geist, Geist_Mono,Hind_Siliguri } from "next/font/google";
import "./globals.css";
import HeaderPage from "@/components/Header";
import NavLinks from "@/components/NavLinks";
import Marquee from "@/components/Marquee";
import { Suspense } from "react";


const hindSiliguri = Hind_Siliguri({
  subsets: ["latin","bengali"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-hind-siliguri",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="bn"
      className={`${geistSans.variable} ${geistMono.variable} ${hindSiliguri.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col ">
        
        <HeaderPage/>
       <Suspense fallback={<h1>Loading....</h1>}> <NavLinks/></Suspense>
        <Marquee/>
       <main>
         {children}
       </main>
        
        
        </body>
    </html>
  );
}
